"""Compile reviewed roster rules using canonical skill values at every level.

Integer coefficients refer to an index in the source skill's values array;
floating point coefficients are fixed game constants. No interpolated levels.
Run from the engine directory with ``python -m runner.complete_roster``.
"""
from __future__ import annotations

import copy
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = json.loads((ROOT / 'scraper/nikke_scraped.json').read_text(encoding='utf-8'))
COOLDOWNS = json.loads((ROOT / 'data/skill_cooldowns.json').read_text(encoding='utf-8'))['characters']
KITS: dict[str, list[dict]] = {}
_name = ''
_favorite = 0
INSTANT = {'heal_hp_pct', 'cover_heal_pct', 'cover_heal_hp_pct', 'cover_revive_pct',
           'revive_hp_pct', 'shield_restore_pct', 'decoy_heal_pct', 'current_hp_reduce',
           'ammo_charge_pct', 'ammo_charge_flat', 'burst_charge_pct', 'burst_cooldown_reduce',
           'buff_stack_add', 'remove_named_buff', 'debuff_cleanse', 'buff_duration_extend',
           'gauge_charge', 'gauge_consume'}


def kit(name: str, favorite: int = 0):
    global _name, _favorite
    assert name in RAW, name
    _name, _favorite = name, favorite
    KITS.setdefault(name, [])


def source(slot: int):
    if _favorite:
        item = next(x for x in RAW[_name]['애장품']['단계별'] if x['단계'] == _favorite)
        assert item['교체슬롯'] == slot
        return item['스킬명'], item
    return list(RAW[_name]['스킬'].items())[slot - 1]


def values(slot: int, value):
    if isinstance(value, int):
        return {'values': {lv: float(v[value]) for lv, v in source(slot)[1]['values'].items()}}
    return {} if value is None else {'fixed_value': float(value)}


def e(slot, timing, target, stat, value=None, duration=None, condition='', name=None,
      stack=1, negative=False, bullets=None, **extra):
    title, raw = source(slot)
    if stat == 'hp_consume_pct':
        stat = 'current_hp_reduce'
    if stat and stat.startswith('burst_reenter:'):
        stat = 'burst_stage_override:reenter' + stat.split(':')[1]
    if timing == 'cd':
        cd = COOLDOWNS.get(_name, {}).get(str(slot))
        if not cd:
            raise ValueError(f'Missing native cooldown: {_name} skill {slot}')
        timing = f'every:{cd:g}s'
    timings = timing if isinstance(timing, list) else [timing]
    kind = ('instant' if stat in INSTANT else
            'damage' if stat and stat.split(':')[0].endswith('damage') else 'buff')
    ef = {'source': f'스킬{slot}', 'type': kind,
          'name': name or f'{title} [{sum(x["source"] == f"스킬{slot}" and x.get("favorite", 0) == _favorite for x in KITS[_name]) + 1}]',
          'trigger': {'timing': timings, 'condition': condition.split('|') if condition else []},
          'target': target}
    if stat:
        ef['stat'] = stat
    ef.update(values(slot, value))
    if negative:
        if 'values' in ef:
            ef['values'] = {k: -v for k, v in ef['values'].items()}
        elif 'fixed_value' in ef:
            ef['fixed_value'] *= -1
    if _favorite:
        ef['favorite'] = _favorite
    if kind == 'buff':
        if duration is None and bullets is None:
            raise ValueError(f'Missing duration: {_name} {title} {stat}')
        enemy_target = target.startswith(('enemy', 'enemies', 'target', 'all_enemies'))
        mitigation = (stat or '').startswith('received_dmg') and negative and not enemy_target
        ef.update(polarity='harmful' if (negative and not mitigation) or (enemy_target and stat != 'taunt') else 'beneficial', max_stack=stack)
    if duration is not None:
        ef['duration'] = duration
    if 'duration_values' in extra:
        ef.pop('duration', None)
    if bullets is not None:
        ef.update(duration=-1, duration_bullets=bullets)
    ef.update(extra)
    if condition and 'passive' not in timings and 'caster_alive' not in condition.split('|'):
        ef['trigger_only_conditions'] = True
    KITS[_name].append(ef)
    return ef


def heal(slot, timing, target='all_allies', value=0, duration=None, condition='', **kw):
    return e(slot, timing, target, 'heal_hp_pct', value, duration, condition,
             scaling='max_hp', heal_basis='caster_max_hp', **({'tick_interval': 1.0} if duration else {}), **kw)


def pair(slot, timing, target, stats, duration, condition='', **kw):
    for stat, value in stats:
        e(slot, timing, target, stat, value, duration, condition, **kw)


def shield(slot, timing, target='self', value=0, duration=-1, condition='', name=None, shared=False):
    return e(slot, timing, target, 'shared_shield_from_max_hp_pct' if shared else 'shield_from_max_hp_pct', value, duration, condition, name)


def damage(slot=3, timing='burst_cast', target='all_enemies', value=0, condition='', stat='burst_damage', **kw):
    return e(slot, timing, target, stat, value, condition=condition, **kw)


def weapon(slot, value, weapon_type, duration, **kw):
    ef = e(slot, 'burst_cast', 'self', None, duration=duration, name=kw.pop('name', '무기 변경'))
    ef.update(type='weapon_change', weapon_type=weapon_type,
              damage_coeff=values(slot, value).get('values', value), **kw)
    ef.pop('polarity', None); ef.pop('max_stack', None)
    return ef


def reenter(stage):
    e(3, 'burst_cast', 'all_allies', f'burst_reenter:{stage}', duration=-1)


def build():
    # Counters and early Elysion roster.
    kit('라피')
    e(1, 'received_hit:20', 'self', 'atk_pct', 0, 20)
    damage(2, 'cd', 'enemies_top_atk:1', stat='damage')
    e(2, 'cd', 'enemies_top_atk:1', 'taunt', duration=5)
    damage(target='enemies_top_atk:1'); e(3, 'burst_cast', 'self', 'atk_pct', 1, 10)
    kit('네온')
    e(1, 'enemy_death', 'allies_top_atk:2', 'crit_rate', 0, 5)
    e(2, 'full_burst_start', 'all_allies', 'crit_rate', 0, bullets=2)
    damage(target='enemies_top_def:1'); e(3, 'burst_cast', 'allies_weapon:SG', 'max_ammo_flat', 3.0, 10)
    kit('아니스')
    e(1, 'received_hit:40', 'self', 'def_pct', 0, 10)
    e(2, 'cd', 'self_and_top_atk:2', 'def_pct', 0, 5)
    e(2, 'cd', 'self_and_top_atk:2', 'damage_share', duration=10)
    damage(target='enemies_in_range', stat='damage'); e(3, 'burst_cast', 'enemies_in_range', 'def_pct', 1, 5, negative=True)
    kit('네온 : 블루 오션')
    for i in range(3):
        e(1, f'burst_cast_count:{i+1}', 'self', 'part_dmg_pct', i, 20)
        e(2, f'burst_enter_count:3:{i+1}', 'self', 'element_bonus_pct', i, 10)
    # Native c014_ulti: shot 1001402, 90 rounds/minute, seven-round launcher.
    weapon(3, 0, 'RL', 7, charge=False, fire_rate=1.5, max_ammo=7,
           reload_time=2.5, pellets=1, muzzles=1, burst_energy=1.25)
    damage(3, 'weapon_hit:무기 변경', 'target', 1, 'target_code:작열', stat='bonus_damage')
    kit('델타')
    e(1, 'full_charge', 'self', 'max_hp_pct', 0, 10)
    e(2, 'burst_cast', 'self', 'def_pct', 0, 20)
    e(3, 'burst_cast', 'self', 'decoy', 0, 10)
    e(3, 'burst_cast', 'self', 'taunt', duration=10, name='주목')
    kit('시그널')
    pair(1, 'hit_count:60', 'target', [('def_pct', 0), ('atk_pct', 1)], 5, negative=True)
    e(2, 'full_burst_start', 'self', 'lifesteal_pct', 0, 10)
    damage(target='enemies_in_range', stat='damage'); e(3, 'burst_cast', 'enemies_in_range', 'def_pct', 1, 10, negative=True)
    kit('폴리')
    e(1, 'on_attack_count:5', 'all_allies', 'atk_pct', 0, 10)
    pair(2, 'cd', 'self_and_lowest_hp:2', [('def_pct', 0), ('damage_share', None)], 10)
    shield(3, 'burst_cast', value=0, duration=10, shared=True)
    e(3, 'burst_cast', 'all_allies', 'atk_pct', 1, 10)
    kit('폴리', 1)
    e(1, 'on_attack_count:5', 'all_allies', 'atk_pct', 0, 10)
    shield(1, 'battle_start', value=1, duration=10, name='폴리스 뱃지')
    kit('폴리', 2)
    e(3, 'burst_cast', 'self', 'undying', duration=5, condition='self_state:폴리스 뱃지')
    e(3, 'burst_cast', 'self', 'remove_named_buff', condition='self_state:폴리스 뱃지', target_effect='폴리스 뱃지')
    shield(3, 'burst_cast', duration=10, shared=True)
    e(3, 'burst_cast', 'all_allies', 'atk_pct', 1, 10)
    kit('폴리', 3)
    pair(2, 'every:20s', 'self_and_lowest_hp:2', [('def_pct', 0), ('damage_share', None)], 10)
    heal(2, 'event:state_end:폴리스 뱃지', 'self', 1, 5)
    kit('키리')
    e(1, 'full_charge_hit', 'target', 'atk_caster_based_pct', 0, 3, negative=True)
    e(1, 'full_charge', 'allies_class:방어형:2', 'atk_caster_based_pct', 1, 3)
    e(2, 'battle_start', 'allies_class:방어형:2', 'max_hp_pct', 0, -1)
    heal(3, 'burst_cast', value=0, duration=10)
    e(3, 'burst_cast', 'allies_class:방어형', 'crit_rate', 1, 10)
    kit('D')
    pair(1, 'full_burst_start', 'self', [('element_bonus_pct', 0), ('lifesteal_pct', 1)], 15)
    e(1, 'full_burst_start', 'self', 'lifesteal_pct', 2, 15, max_trigger=1)
    e(2, 'event:target_spawn', 'all_allies', 'burst_charge_pct', 0, max_trigger=1)
    e(2, 'event:target_spawn', 'all_allies', 'stun_immune', duration=-1, duration_values=values(2, 1)['values'], name='기절 면역')
    e(2, 'event:target_spawn', 'self', 'element_bonus_pct', 2, 15)
    damage(); e(3, 'burst_cast', 'allies_class:화력형', 'part_dmg_pct', 1, 15)
    e(3, 'burst_cast', 'all_allies', 'fullburst_duration', 5.04, -1, 'self_state:기절 면역')
    kit('벨로타')
    e(1, 'full_charge', 'self', 'explosion_range', 0, 5)
    e(2, 'multi_hit:4', 'target', 'def_pct', 0, 5, negative=True)
    damage(2, 'multi_hit:4', 'target', 1, stat='bonus_damage')
    damage(target='enemies_in_range', stat='damage'); e(3, 'burst_cast', 'all_allies', 'charge_speed_pct', 1, 10)
    kit('미카')
    e(1, 'received_hit:20', 'self', 'def_pct', 0, 10)
    pair(2, 'cd', 'allies_top_atk:2', [('max_ammo_flat', 2.0), ('def_pct', 0)], 10)
    damage(); e(3, 'burst_cast', 'all_enemies', 'def_pct', 1, 5, negative=True)
    kit('미카 : 스노우 버디')
    e(1, 'hit_count:120', 'all_allies', 'received_dmg_pct', 0, 15, name='정리정돈', stack=10, negative=True)
    e(1, 'passive', 'all_allies', 'max_ammo_pct', 1, -1, 'self_stack_above:정리정돈:10')
    e(2, 'hit_count:{0}', 'all_allies', 'buff_stack_add', 1.0, trigger_values=values(2, 0)['values'])
    e(2, 'battle_start', 'self', 'burst_charge_speed_pct', 1, -1)
    e(3, 'burst_cast', 'all_allies', 'debuff_cleanse', 1.0)
    e(3, 'burst_cast', 'all_allies', 'atk_caster_based_pct', 0, 5)
    kit('브리드')
    e(1, 'on_attack_count:30', 'self', 'atk_pct', 0, 10)
    damage(2, 'cd', 'enemies_top_def:1', stat='damage')
    damage(target='enemies_top_def:1'); damage(target='enemies_top_def:1', value=1, condition='self_hp_max', stat='bonus_damage')
    kit('솔린')
    e(1, 'on_attack_count:40', 'self', 'attack_speed_pct', 0, 3)
    pair(2, 'passive', 'self', [('crit_rate', 0), ('crit_dmg', 1)], -1, 'self_hp_max')
    damage(target='enemies_in_range', stat='damage'); damage(target='enemies_in_range', value=1, condition='self_hp_max', stat='bonus_damage')
    for fav in range(4):
        kit('디젤', fav)
        if fav in (0, 3):
            e(1, 'full_burst_start', 'self', 'def_pct', 0, 10)
            heal(1, 'received_hit', 'self', 1, condition='self_state:주목' if fav else 'during_full_burst')
            if fav: e(1, 'hit_count:150', 'self', 'buff_stack_add', 1.0, condition='self_state:주목')
        if fav in (0, 1):
            e(2, 'hit_count:70' if fav else 'hit_count:100', 'self', 'max_ammo_pct', 0, 10, name='딸기 사탕', stack=10)
            e(2, 'event:딸기 사탕', 'all_allies', 'ammo_charge_pct', 1, condition='self_stack_above:딸기 사탕:10')
            if fav: e(2, 'event:딸기 사탕', 'all_allies', 'pierce_dmg_pct', 2, 10, 'self_stack_above:딸기 사탕:10')
            e(2, 'event:딸기 사탕', 'self', 'remove_named_buff', condition='self_stack_above:딸기 사탕:10', target_effect='딸기 사탕')
        if fav in (0, 2):
            damage(target='enemies_top_atk:5', stat='damage')
            if fav:
                e(3, 'burst_cast', 'self', 'max_hp_only_pct', 1, 10)
                e(3, 'burst_cast', 'self', 'taunt', duration=10, name='주목')
            else: e(3, 'burst_cast', 'enemies_top_atk:5', 'taunt', duration=-1, duration_values=values(3, 1)['values'])
    kit('엠마')
    heal(1, 'received_hit', condition='prob:5')
    e(2, 'passive', 'all_allies', 'heal_received_pct', 0, -1, 'self_hp_above:90')
    heal(3, 'burst_cast'); e(3, 'burst_cast', 'all_allies', 'lifesteal_pct', 1, 5)
    kit('베스티')
    e(1, 'full_charge', 'self', 'explosion_range', 0, 10)
    for i, st in enumerate(['atk_pct', 'crit_dmg', 'crit_rate']):
        e(2, f'burst_cast_count:{i+1}', 'self', st, i, 45, name=f'생존본능 {i+1}')
    damage(stat='damage:2', target='enemies_lowest_hp:1', duration=18, tick_interval=1.0)
    for i in range(1, 4): damage(value=i, condition=f'self_state:생존본능 {i}', stat='bonus_damage')
    e(3, 'burst_cast', 'all_allies', 'fullburst_duration', -5.0, -1)
    kit('은화')
    pair(1, 'last_bullet_fire', 'self', [('charge_dmg_pct', 0), ('charge_speed_pct', 1)], -1, bullets=2)
    e(2, 'last_bullet_fire', 'target', 'def_pct', 0, 5, negative=True)
    damage(target='enemies_top_atk:10', stat='damage')
    e(3, 'burst_cast', 'enemies_top_atk:10', 'def_pct', 1, 15, negative=True)
    e(3, 'burst_cast', 'all_allies', 'crit_rate', 2, 15)
    kit('크로우')
    e(1, 'full_burst_start', 'all_enemies', 'atk_pct', 0, 10, negative=True)
    damage(2, 'last_bullet', 'target', stat='bonus_damage')
    e(2, 'last_bullet', 'self', 'def_pct', 1, 5)
    damage(target='enemies_top_atk:1')
    kit('자칼')
    e(1, 'received_hit:10', 'enemies_top_hp:1', 'received_dmg_pct', 0, 10)
    e(1, 'received_hit:10', 'enemies_top_hp:1', 'atk_pct', 1, 10, negative=True)
    pair(2, 'battle_start', 'self_and_top_atk:2', [('damage_share', None), ('def_pct', 0)], 120)
    e(3, 'burst_cast', 'all_allies', 'burst_dmg_single_pct', 0, 15)
    e(3, 'burst_cast', 'all_allies', 'def_pct', 1, 10)
    for fav in range(4):
        kit('바이퍼', fav)
        if fav in (0, 1):
            pair(1, 'event:target_spawn', 'all_allies', [('atk_pct', 0), ('accuracy_pct', 1)], 10)
            if fav: pair(1, 'on_attack', 'self', [('dot_dmg_pct', 2), ('accuracy_pct', 3)], 10, 'self_state:애교', stack=10)
        if fav in (0, 3):
            e(2, 'passive', 'self', 'accuracy_pct', 0, -1)
            e(2, 'full_burst_start', 'self', 'stealth', duration=-1 if fav else 10, name='애교')
            e(2, 'received_hit', 'self', 'remove_named_buff', target_effect='애교')
            e(2, 'full_burst_start', 'self', 'invincible', duration=1)
            if fav: e(2, 'burst_cast', 'all_allies', 'burst_reenter:2', duration=-1)
        if fav in (0, 2):
            damage(target='enemies_target:1', stat='damage')
            e(3, 'burst_cast', 'enemies_target:1', 'def_pct', 1, 10, 'target_is_boss', negative=True)
            if fav: damage(value=2, target='enemies_target:1', condition='target_is_boss', stat='dot_damage', duration=10, tick_interval=1.0)
    kit('N102')
    pair(1, 'full_charge', 'allies_top_atk:1', [('max_ammo_flat', 3.0), ('crit_dmg', 0)], 10)
    e(2, 'cd', 'allies_top_atk:1', 'charge_dmg_pct', 0, 5)
    e(3, 'burst_cast', 'all_allies', 'atk_pct', 0, 10)
    kit('앤 : 미라클 페어리')
    e(1, 'on_attack_count:3', 'allies_class:지원형', 'lifesteal_pct', 0, 5)
    e(2, 'passive', 'all_allies', 'heal_received_pct', 0, -1, 'self_hp_above:90')
    e(2, 'last_bullet', 'all_enemies', 'heal_received_pct', 1, 10, 'self_hp_above:90', negative=True)
    heal(3, 'burst_cast', 'allies_class:화력형')
    e(3, 'burst_cast', 'allies_class:화력형', 'atk_pct', 1, 10)
    e(3, 'burst_cast', 'allies_down_class_random:화력형:1', 'revive_hp_pct', 2, max_trigger=1)
    kit('메어리')
    heal(1, 'last_bullet', 'allies_lowest_hp_ratio:1')
    e(2, 'full_burst_start', 'all_allies', 'heal_received_pct', 0, 15)
    heal(3, 'burst_cast'); e(3, 'burst_cast', 'all_allies', 'def_pct', 1, 10, 'self_hp_above:50')
    kit('페퍼')
    heal(1, 'last_bullet', 'allies_lowest_hp_ratio:1')
    e(1, 'last_bullet', 'all_allies', 'heal_received_pct', 1, 15, name='리프레쉬 하트', stack=5)
    damage(2, 'cd', 'enemies_top_atk:1', stat='damage')
    e(2, 'cd', 'enemies_top_atk:1', 'atk_pct', 1, 5, negative=True)
    damage(target='enemies_top_atk:1'); e(3, 'burst_cast', 'all_allies', 'buff_stack_add', 1.0)
    heal(3, 'burst_cast', value=1, condition='self_stack_above:리프레쉬 하트:5')
    kit('메어리 : 베이 갓데스')
    for i in range(3):
        heal(1, f'full_burst_start_count:{i+1}', value=i, duration=5)
        e(2, f'burst_cast_count:{i+1}', 'allies_code:수냉', 'element_bonus_pct', i, [3, 5, 10][i])
    e(3, 'burst_cast', 'allies_code:수냉', 'atk_pct', 0, 3)
    e(3, 'burst_cast', 'all_allies', 'hp_caster_based_pct', 1, 10)
    for fav in range(4):
        kit('밀크', fav)
        if fav in (0, 1):
            e(1, 'cd', f'allies_top_atk:{3 if fav else 2}', 'atk_pct', 0, 10)
            if fav: e(1, 'battle_start', 'self', 'burst_cooldown', 20.0, -1)
        if fav in (0, 2):
            e(2, 'passive', 'all_allies', 'crit_dmg', 0, -1, 'self_hp_above:80')
            if fav: e(2, 'full_charge_hit_count:10', 'all_allies', 'burst_cooldown_reduce', 1)
        if fav in (0, 3):
            damage(target='enemies_top_def:1'); e(3, 'burst_cast', 'all_allies', 'lifesteal_pct', 1, 10)
            if fav: e(3, 'burst_cast', 'all_allies', 'heal_received_pct', 2, 10)
    for fav in range(4):
        kit('프림', fav)
        if fav == 0: e(1, 'hit_count:4', 'target', 'def_pct', 0, 10, negative=True)
        if fav == 1:
            e(1, 'full_charge_hit', 'target', 'def_pct', 0, 10, name='잠 옴', stack=5, negative=True)
            e(1, 'full_charge_hit_count:6', 'self', 'armor_break_enabled', duration=10, condition='target_stack_above:잠 옴:5', name='일어남')
        if fav in (0, 3):
            e(2, 'full_charge', 'all_allies', 'max_hp_pct', 0, 4)
            if fav: e(2, 'full_charge', 'all_allies', 'armor_break_dmg_pct', 1, 5, 'self_state:일어남')
        if fav in (0, 2):
            damage(target='enemies_top_def:10', stat='damage')
            e(3, 'burst_cast', 'enemies_top_def:10', 'def_pct', 1, 10, negative=True)
            e(3, 'burst_cast', 'all_allies', 'max_hp_pct', 2, 4)
            if fav: e(3, 'burst_cast', 'all_allies', 'armor_break_dmg_pct', 3, 10, 'self_state:일어남')
    kit('유니')
    e(1, 'full_burst_start', 'all_allies', 'charge_speed_pct', 0, 10)
    pair(2, 'full_charge', 'all_allies', [('def_pct', 0), ('lifesteal_pct', 1)], 10)
    e(2, 'full_charge', 'all_allies', 'max_ammo_flat', 1.0, 5)
    damage(target='enemies_in_range', stat='damage'); e(3, 'burst_cast', 'enemies_in_range', 'enemy_movement_disable', duration=5)
    kit('미하라')
    e(1, 'last_bullet', 'self', 'crit_dmg', 0, 10)
    e(2, 'burst_cast_count:1', 'self', 'atk_pct', 0, 45, name='페인 로드 1')
    e(2, 'burst_cast_count:2', 'self', 'crit_rate', 1, 45, name='페인 로드 2')
    e(3, 'burst_cast', 'all_allies', 'fullburst_duration', -5.0, -1)
    damage(); damage(value=1, condition='self_state:페인 로드 2', stat='bonus_damage')
    kit('율하')
    e(1, 'received_hit:30', 'self', 'crit_rate', 0, 20, name='평정심')
    e(2, 'cd', 'all_allies', 'atk_pct', 0, 5); e(2, 'cd', 'all_allies', 'damage_share', duration=10)
    damage(); damage(value=1, condition='self_state:평정심', stat='bonus_damage')
    kit('애드미')
    e(1, 'received_hit:20', 'all_allies', 'charge_dmg_mag_pct', 0, 20)
    e(2, 'cd', 'allies_top_atk:2', 'received_dmg_pct', 0, 10, negative=True)
    pair(3, 'burst_cast', 'all_allies', [('reload_speed_pct', 0), ('crit_dmg', 1)], 10)
    kit('길로틴')
    e(1, 'hit_count:30', 'self', 'crit_rate', 0, 10); e(1, 'hit_count:30', 'self', 'hp_consume_pct', 2.01)
    e(2, 'hit_count:150', 'self', 'crit_dmg', 0, 5)
    e(2, 'passive', 'self', 'atk_pct', 1, -1, 'self_hp_below:70', scaling='lost_hp_pct')
    damage(target='enemies_top_atk:1'); damage(target='enemies_top_atk:1', value=1, condition='self_hp_below:50', stat='bonus_damage')
    kit('메이든')
    e(1, 'received_hit:20', 'self', 'atk_pct', 0, 20, name='복수')
    e(2, 'cd', 'all_enemies', 'taunt', duration=10); e(2, 'cd', 'self', 'crit_dmg', 0, 10)
    damage(); damage(value=1, condition='self_state:복수', stat='bonus_damage')
    kit('루드밀라')
    pair(1, 'last_bullet', 'target', [('def_pct', 0), ('atk_pct', 1)], 10, negative=True)
    e(2, 'full_burst_start', 'all_enemies', 'taunt', duration=15.09, name='주목')
    e(2, 'full_burst_start', 'self', 'received_dmg_pct', 0, 15, negative=True)
    damage(target='enemies_top_atk:10', stat='damage'); e(3, 'burst_cast', 'all_allies', 'def_pct', 1, 10, 'self_hp_above:50')
    kit('네베')
    damage(1, 'cd', 'enemies_lowest_hp:1', stat='damage')
    pair(2, 'full_burst_start', 'self', [('pierce_enabled', None), ('atk_pct', 0)], -1, bullets=2)
    pair(3, 'burst_cast', 'self', [('crit_rate', 0), ('accuracy_pct', 1)], 20)

    kit('앨리스 : 원더랜드 바니')
    heal(1, 'on_attack_count:60')
    e(1, 'on_attack_count:60', 'all_allies', 'qte_dmg_pct', 1, 5, name='당근 파티', stack=5)
    e(1, 'on_attack_count:90', 'allies_code:수냉', 'buff_stack_add', 1.0)
    e(2, 'full_burst_end', 'all_allies', 'burst_charge_speed_pct', 0, 5)
    e(2, 'full_burst_start', 'all_allies', 'max_ammo_pct', 1, 15)
    e(2, 'full_burst_start', 'all_allies', 'ammo_charge_pct', 2)
    reenter(1); heal(3, 'burst_cast')
    e(3, 'burst_cast', 'all_allies', 'heal_received_pct', 1, 15, 'self_stack_above:당근 파티:5')
    kit('루피')
    e(1, 'hit_count:100', 'allies_code:철갑', 'buff_stack_add', 1.0)
    e(1, 'hit_count:100', 'allies_code:철갑', 'crit_rate', 0, 10)
    e(2, 'on_attack_count:30', 'self', 'atk_pct', 0, 15, name='마일리지', stack=5)
    damage(target='enemies_in_range', stat='damage')
    e(3, 'burst_cast', 'all_allies', 'atk_pct', 1, 5, 'self_stack_above:마일리지:5')
    kit('얀')
    e(1, 'full_burst_start', 'all_allies', 'charge_dmg_pct', 0, 10)
    pair(2, 'full_charge', 'all_allies', [('atk_pct', 0), ('crit_rate', 1)], 5)
    damage(target='enemies_in_range', stat='damage')
    e(3, 'burst_cast', 'enemies_in_range', 'enemy_pull', duration=2)
    kit('루피 : 윈터 쇼퍼')
    e(1, 'last_bullet', 'all_allies', 'def_pct', 0, 5)
    e(2, 'event:ally_burst_cast', 'all_allies', 'def_pct', 0, 20, name='쇼핑', stack=4)
    e(2, 'full_burst_end', 'all_allies', 'burst_charge_speed_pct', 1, 5, 'self_stack_above:쇼핑:4')
    e(3, 'burst_cast', 'self', 'taunt', duration=5, name='주목')
    e(3, 'burst_cast', 'self', 'lifesteal_pct', 0, 10)
    e(3, 'burst_cast', 'all_allies', 'reload_speed_pct', 1, 10); reenter(1)
    for fav in range(4):
        kit('엑시아', fav)
        if fav in (0, 3):
            pair(1, 'last_bullet', 'target', [('atk_pct', 0), ('def_pct', 1)], 5, 'self_state:해킹 코드 수집', negative=True)
            if fav: e(1, 'full_burst_start', 'self', 'reload_speed_fixed', 95.0, 10)
        if fav in (0, 1):
            e(2, 'full_charge_hit' if fav else 'last_bullet', 'self', 'atk_pct', 0, 5 if fav else 15, name='해킹 코드 수집', stack=5)
            if fav: e(2, 'last_bullet', 'allies_code:전격', 'atk_caster_based_pct', 1, 15, 'self_state:해킹 코드 수집', stack=5)
        if fav in (0, 2):
            damage(target='enemies_top_def:10', stat='damage')
            e(3, 'burst_cast', 'enemies_top_def:10', 'def_pct', 1, 5, negative=True)
            damage(target='enemies_top_def:10', value=2, condition='self_stack_above:해킹 코드 수집:5', stat='bonus_damage')
            if fav: e(3, 'burst_cast', 'enemies_top_def:10', 'received_dmg_pct', 3, 10, 'self_stack_above:해킹 코드 수집:5')
    kit('노벨')
    damage(1, 'cd', 'enemies_top_def:3', stat='damage')
    e(1, 'cd', 'enemies_top_def:3', 'def_pct', 1, 5, negative=True)
    e(2, 'hit_count:100', 'self', 'def_pct', 0, 15, name='증거품 수집', stack=5)
    damage(target='enemies_top_atk:1')
    e(3, 'burst_cast', 'enemies_top_atk:1', 'received_dmg_pct', 1, 5, 'self_stack_above:증거품 수집:5')
    kit('라푼젤')
    heal(1, 'full_charge', 'allies_lowest_hp_ratio:3')
    pair(2, 'cd', 'allies_top_atk:2', [('max_hp_pct', 0), ('heal_received_pct', 1)], 15)
    heal(3, 'burst_cast'); e(3, 'burst_cast', 'allies_down_top_atk:1', 'revive_hp_pct', 1)
    e(3, 'burst_cast', 'all_enemies', 'stun', duration=1, condition='self_hp_below:30')
    kit('스노우 화이트 : 이노센트 데이즈')
    e(1, 'hit_count:30', 'self', 'max_ammo_pct', 0, 5, stack=5)
    damage(1, 'hit_count:30', 'enemies_in_range', 1, stat='damage')
    damage(2, 'hit_count:50', 'all_enemies', stat='damage', name='세븐스 드워프 IV')
    e(2, 'burst_cast', 'self', 'atk_dmg_pct', 1, 10)
    e(3, 'burst_cast', 'self', 'trigger_count_reduce', 20.0, 10, target_effect='세븐스 드워프 IV')
    pair(3, 'burst_cast', 'self', [('atk_pct', 0), ('infinite_ammo', None)], 10)
    kit('라푼젤 : 퓨어 그레이스')
    shield(1, 'battle_start', shared=True, name='생츄어리')
    shield(1, 'burst_cast', value=1, shared=True, name='생츄어리')
    e(1, 'charge_hold:1', 'all_allies', 'atk_dmg_pct', 2, -1, 'during_shield|during_charge_hold:1')
    heal(2, 'full_charge', 'self')
    e(2, 'charge_hold:1', 'self', 'hp_consume_pct', 2.0, -1, 'during_shield|during_charge_hold:1', tick_interval=1.0)
    e(2, 'charge_hold:1', 'self', 'shield_restore_pct', 1, -1, 'during_shield|during_charge_hold:1', tick_interval=1.0)
    e(3, 'burst_cast', 'self', 'max_hp_pct', 0, 10)
    e(3, 'burst_cast', 'all_allies', 'atk_dmg_pct', 1, 10)
    kit('하란')
    damage(1, 'on_attack', 'target', stat='dot_damage', condition='prob:25', duration=5, tick_interval=1.0, name='바이러스 전이')
    damage(1, 'enemy_death', 'enemies_nearest:2', 1, 'target_state:바이러스 전이', stat='dot_damage', duration=5, tick_interval=1.0, name='바이러스 전이 확산')
    pair(2, 'full_charge', 'self', [('pierce_enabled', None), ('crit_rate', 0)], -1, bullets=1)
    e(2, 'enemy_death', 'self', 'atk_pct', 1, 10, stack=15)
    damage()
    kit('노아')
    e(1, 'received_hit', 'all_allies', 'received_dmg_pct', 0, 10, 'prob:10', negative=True)
    e(2, 'full_charge_hit', 'target', 'taunt', duration=2)
    e(2, 'full_charge_hit', 'target', 'atk_pct', 0, 5, negative=True)
    e(3, 'burst_cast', 'self', 'taunt', duration=10, name='주목')
    e(3, 'burst_cast', 'all_allies', 'invincible', duration=3)
    e(3, 'burst_cast', 'all_allies', 'def_pct', 0, 10)
    kit('도로시')
    e(1, 'last_bullet_fire', 'all_allies', 'burst_cooldown_reduce', 0)
    e(1, 'last_bullet_fire', 'all_allies', 'part_dmg_pct', 1, 5, 'self_state:발현')
    damage(2, 'every:20s', 'all_enemies', stat='split_damage', name='초토화')
    e(3, 'burst_cast', 'self', 'effect_interval', -18.0, 10, name='발현', target_effect='초토화')
    e(3, 'burst_cast', 'self', 'pierce_enabled', duration=10)
    e(3, 'burst_cast', 'enemies_target:1', 'damage_accumulate', 0, 10, name='낙인', accumulate_source='squad', accumulate_ratio=100.0, detonate_at_cap=False)
    kit('루마니')
    e(1, 'full_charge', 'self', 'max_hp_pct', 0, 2, name='머슬 업', stack=5)
    e(1, 'full_charge_hit', 'target', 'taunt', duration=5, condition='during_full_burst')
    e(2, 'part_hit_count:5', 'all_allies', 'part_dmg_pct', 0, 5)
    e(3, 'burst_cast', 'self', 'max_hp_pct', 0, 10)
    e(3, 'burst_cast', 'all_allies', 'normal_atk_dmg_pct', 1, 10)
    e(3, 'burst_cast', 'self', 'received_dmg_pct', 2, 10, 'self_stack_above:머슬 업:5', negative=True)
    kit('에피넬')
    e(1, 'enemy_death', 'self', 'atk_pct', 0, 15, name='슈퍼 루키', stack=5)
    pair(2, 'last_bullet', 'self', [('crit_rate', 0), ('crit_dmg', 1)], 5)
    damage(); damage(value=1, condition='self_stack_above:슈퍼 루키:5', stat='bonus_damage')
    kit('폴크방')
    shield(1, 'cd', 'allies_top_atk:2', duration=10)
    e(1, 'cd', 'allies_top_atk:2', 'heal_received_pct', 1, 10)
    e(2, 'cd', 'enemies_top_atk:1', 'taunt', duration=5)
    e(2, 'cd', 'self', 'max_hp_pct', 0, 10)
    shield(3, 'burst_cast', 'allies_top_atk:2', duration=10)
    e(3, 'burst_cast', 'allies_top_atk:2', 'lifesteal_pct', 1, 10)
    kit('니힐리스타')
    pair(1, 'full_charge', 'self', [('pierce_enabled', None), ('pierce_range_pct', 50.0)], -1, bullets=1)
    damage(1, 'multi_hit:2', 'target', stat='bonus_damage')
    damage(2, 'cd', 'enemies_in_range', stat='damage')
    damage(target='enemies_in_range', stat='damage')
    damage(target='enemies_in_range', value=1, stat='dot_damage', duration=10, tick_interval=1.0, name='화상')
    e(3, 'burst_cast', 'self', 'max_ammo_flat', 2, 15)
    kit('사쿠라')
    e(1, 'on_attack_count:3', 'all_allies', 'def_pct', 0, 15, name='벚꽃차', stack=10)
    e(2, 'passive', 'all_allies', 'projectile_dmg_pct', 0, -1)
    e(2, 'full_burst_start', 'all_allies', 'burst_cooldown_reduce', 1)
    e(3, 'burst_cast', 'all_allies', 'received_dmg_from_code:풍압', 0, 30, negative=True, max_trigger=1)
    e(3, 'burst_cast', 'all_allies', 'atk_caster_based_pct', 1, 10)
    e(3, 'burst_cast', 'all_allies', 'qte_dmg_pct', 2, 30, 'self_stack_above:벚꽃차:10')
    kit('에테르')
    e(1, 'cd', 'allies_lowest_hp:1', 'received_dmg_pct', 0, 5, negative=True)
    damage(2, 'cd', 'enemies_top_def:3', stat='damage')
    e(2, 'cd', 'enemies_top_def:3', 'def_pct', 1, 6, 'during_full_burst', negative=True)
    shield(3, 'burst_cast', 'allies_lowest_hp:3', duration=5)
    kit('솔져 E.G.')
    e(1, 'hit_count:1', 'self', 'atk_pct', 0, 5, 'prob:5')
    e(2, 'cd', 'self', 'max_ammo_pct', 0, 5)
    damage(target='enemies_in_range', stat='damage')
    kit('솔져 F.A.')
    e(1, 'received_hit', 'self', 'def_pct', 0, 10, 'prob:10')
    e(2, 'cd', 'self', 'lifesteal_pct', 0, 8)
    e(3, 'burst_cast', 'self', 'max_hp_pct', 0, 10)
    kit('프로덕트 08')
    e(1, 'hit_count:1', 'allies_lowest_hp:1', 'def_pct', 0, 5, 'prob:20')
    e(2, 'cd', 'allies_top_atk:1', 'crit_rate', 0, 5)
    e(3, 'burst_cast', 'all_allies', 'atk_pct', 0, 10)
    kit('프로덕트 12')
    e(1, 'on_attack_count:200', 'self', 'atk_pct', 0, 5)
    damage(2, 'cd', 'enemies_lowest_hp:1', stat='damage')
    damage(target='enemies_in_range', stat='damage')
    kit('iDoll 플라워')
    e(1, 'last_bullet', 'target', 'atk_pct', 0, 5, negative=True)
    e(2, 'cd', 'enemies_top_atk:1', 'atk_pct', 0, 5, negative=True)
    damage(target='enemies_top_atk:1'); e(3, 'burst_cast', 'enemies_top_atk:1', 'taunt', duration=2)
    kit('iDoll 오션')
    heal(1, 'last_bullet', 'allies_lowest_hp_ratio:1')
    heal(2, 'cd', 'allies_lowest_hp_ratio:1'); heal(3, 'burst_cast')
    kit('솔져 O.W.')
    damage(1, 'on_attack', 'target', condition='prob:10', stat='bonus_damage')
    e(2, 'cd', 'allies_top_atk:3', 'cover_def_pct', 0, 5)
    e(3, 'burst_cast', 'allies_code:작열', 'max_ammo_pct', 0, -1, duration_values=values(3, 1)['values'])
    kit('프로덕트 23')
    e(1, 'last_bullet', 'self', 'def_pct', 0, 10)
    e(2, 'cd', 'self', 'lifesteal_pct', 0, 10)
    e(3, 'burst_cast', 'enemies_top_atk:2', 'def_pct', 0, 5, negative=True)
    kit('iDoll 썬')
    e(1, 'hit_count:10', 'self', 'def_pct', 0, 5)
    e(2, 'received_hit', 'self', 'atk_pct', 0, 5, 'prob:20')
    e(3, 'burst_cast', 'self', 'max_ammo_pct', 0, 10)
    kit('에이드')
    e(1, 'battle_start', 'all_allies', 'debuff_block_charge', 1.0, -1, name='완벽한 메이드')
    e(1, 'hp_below:90', 'all_allies', 'atk_caster_based_pct', 0, 5)
    e(2, 'on_attack_count:420', 'all_allies', 'debuff_block_charge', 1.0, -1, name='완벽한 메이드')
    e(2, 'on_attack_count:120', 'all_allies', 'hp_only_caster_based_pct', 0, 5)
    pair(3, 'burst_cast', 'all_allies', [('hp_only_caster_based_pct', 0), ('atk_caster_based_pct', 1)], 10)
    kit('코코아')
    e(1, 'cd', 'all_allies', 'cover_heal_pct', 0)
    e(1, 'cd', 'allies_debuff_random:2', 'debuff_cleanse', 1.0)
    e(2, 'full_charge', 'self', 'received_dmg_pct', 0, 5, name='프로 케첩', stack=15, negative=True)
    e(3, 'burst_cast', 'all_allies', 'debuff_cleanse', 1.0)
    e(3, 'burst_cast', 'all_enemies', 'atk_pct', 0, 10, 'self_stack_above:프로 케첩:15', negative=True)
    kit('소다')
    e(1, 'on_attack_count:180', 'self', 'max_hp_pct', 0, 10, name='메이드정신', stack=5)
    heal(2, 'cd'); heal(2, 'cd', value=1, condition='self_stack_above:메이드정신:5')
    damage(target='enemies_random:2', stat='damage')
    e(3, 'burst_cast', 'enemies_random:2', 'stun', duration=1)
    e(3, 'burst_cast', 'allies_code:작열', 'buff_stack_add', 1.0)
    kit('프리바티 : 언카인드 메이드')
    damage(1, 'pellet_hit_count:30', 'enemies_nearest:2', stat='damage')
    e(2, 'pellet_hit_single:5', 'self', 'reload_speed_pct', 0, 2)
    e(2, 'pellet_hit_count:30', 'self', 'ammo_charge_flat', 1.0, condition='during_full_burst')
    e(2, 'pellet_hit_count:30', 'self', 'atk_pct', 1, 2, 'during_full_burst', stack=5)
    pair(3, 'burst_cast', 'self', [('atk_dmg_pct', 0), ('crit_dmg', 1)], 10); damage(value=2)
    kit('마르차나')
    e(1, 'last_bullet', 'all_allies', 'lifesteal_pct', 0, 3)
    e(1, 'last_bullet', 'allies_top_atk:2', 'heal_received_pct', 1, 3)
    heal(2, 'burst_cast')
    pair(3, 'burst_cast', 'all_allies', [('heal_overcharge_store', 0), ('def_caster_based_pct', 1)], 10)
    kit('차임')
    e(1, 'battle_start', 'allies_king', 'atk_caster_based_pct', 0, -1, name='소원')
    e(2, 'full_burst_start', 'allies_king', 'normal_atk_dmg_pct', 0, 10, name='일과 보고')
    reenter(2); e(3, 'burst_cast', 'all_allies', 'max_ammo_pct', 0, 10)
    e(3, 'burst_cast', 'allies_king', 'atk_dmg_pct', 1, 10, name='충심')
    kit('마스트')
    e(1, 'crit_hit_count:2', 'target', 'def_caster_based_pct', 0, 3, name='해풍', stack=50, negative=True)
    e(1, 'passive', 'self_and_top_atk:2', 'crit_dmg', 1, -1, 'self_hp_below:70')
    e(2, 'battle_start', 'self_and_top_atk:2', 'crit_rate', 0, 30)
    pair(3, 'burst_cast', 'self_and_top_atk:2', [('hp_only_caster_based_pct', 0), ('crit_dmg', 1)], 7)
    damage(target='target', value=2, condition='target_state:해풍', stat='dot_damage', duration=7, tick_interval=1.0, name='폭풍', scaling='stack_count', scaling_ref='해풍')
    kit('앵커')
    e(1, 'last_bullet', 'target', 'taunt', duration=5); e(1, 'last_bullet', 'self', 'def_pct', 0, 5)
    e(2, 'battle_start', 'self', 'projectile_dmg_pct', 0, -1); damage()

    kit('킬로')
    shield(1, 'battle_start', name='나노 코팅')
    shield(1, 'burst_cast', value=1, condition='not_self_state:나노 코팅', name='나노 코팅')
    e(2, 'on_attack_count:200', 'self', 'shield_restore_pct', 0, condition='self_state:나노 코팅')
    for i in range(1, 4):
        e(2, f'burst_cast_count:{i}', 'self', 'next_shield_hp_pct', i, -1, 'not_self_state:나노 코팅')
    damage(condition='self_state:나노 코팅', stat='damage', scaling='max_hp_as_atk', scaling_hp_pct=5.0)
    e(3, 'burst_cast', 'self', 'max_hp_pct', 1, 20, 'not_self_state:나노 코팅')
    # Resolve the burst's shield branch and next-shield bonus before recoating.
    for effect in KITS['킬로']:
        effect['event_priority'] = {'스킬3': 0, '스킬2': 1, '스킬1': 2}[effect['source']]
    kit('네로')
    e(1, 'event:heal_received', 'event_healer', 'received_dmg_pct', 0, 5, negative=True)
    e(1, 'event:heal_received', 'self', 'received_dmg_pct', 1, 5, name='고양이 보은', stack=5, negative=True)
    e(2, 'received_hit', 'target', 'received_dmg_pct', 0, 5, 'prob:30')
    damage(2, 'received_hit', 'target', 1, 'self_state:큰 고양이|prob:30', stat='damage')
    e(2, 'battle_start', 'self', 'max_hp_pct', 2, -1)
    damage(target='enemies_top_hp:1')
    e(3, 'burst_cast', 'self', 'taunt', duration=-1, duration_values=values(3, 1)['values'], name='주목')
    e(3, 'burst_cast', 'self', 'heal_received_pct', 2, 15, 'self_stack_above:고양이 보은:5', name='큰 고양이')
    kit('비스킷')
    e(1, 'full_burst_end', 'allies_class:화력형', 'normal_atk_crit_rate', 0, 10)
    heal(1, 'full_burst_end', 'allies_class:화력형', 1, 10)
    e(2, 'event:defender_hp_below:50', 'event_subject', 'invincible', duration=5, max_trigger=2)
    heal(2, 'event:defender_hp_below:50', 'event_subject', max_trigger=2)
    e(3, 'burst_cast', 'allies_broken_cover_random:2', 'cover_revive_pct', 0)
    pair(3, 'burst_cast', 'allies_class:지원형', [('atk_pct', 1), ('lifesteal_pct', 2)], 10)
    kit('라이')
    e(1, 'on_attack_count:60', 'all_allies', 'burst_charge_pct', 0)
    e(1, 'on_attack_count:60', 'self', 'decoy_heal_pct', 1, condition='during_decoy')
    e(2, 'battle_start', 'self', 'decoy', 0, 240)
    e(3, 'burst_cast', 'self', 'taunt', duration=5, name='주목')
    e(3, 'burst_cast', 'self', 'received_dmg_pct', 0, 10, negative=True)
    e(3, 'burst_cast', 'self', 'decoy_heal_pct', 1, 10, 'during_decoy', tick_interval=1.0)
    kit('길티')
    e(1, 'on_attack_count:6', 'self', 'atk_copy', 0, 10, name='빌려 갈게에….', stack=5, copy_target='allies_top_atk:1')
    e(2, 'on_attack_count:12', 'allies_code:풍압', 'buff_stack_add', 1.0)
    e(2, 'on_attack_count:12', 'allies_code:풍압', 'atk_pct', 0, 10)
    damage(target='enemies_top_def:1')
    e(3, 'burst_cast', 'enemies_top_def:1', 'def_pct', 1, 5, 'self_stack_above:빌려 갈게에….:5', negative=True)
    damage(target='enemies_top_def:1', value=2, condition='self_stack_above:빌려 갈게에….:5', stat='bonus_damage')
    kit('신')
    e(1, 'last_bullet_fire', 'self', 'hp_copy', 0, 5, copy_target='allies_top_hp:1')
    e(1, 'last_bullet_fire', 'self', 'taunt', duration=5, name='주목')
    e(2, 'full_burst_end', 'self', 'burst_charge_speed_pct', 0, 5)
    for i, st in enumerate(['lifesteal_pct', 'heal_received_pct', 'def_pct'], 1):
        e(2, f'burst_cast_count:{i}', 'self', st, i, 5)
    e(3, 'burst_cast', 'all_enemies', 'received_dmg_pct', 0, 5, 'enemy_count_above:4')
    damage(target='enemies_in_range', value=1, stat='damage')
    kit('퀀시')
    e(1, 'on_attack_count:60', 'self', 'hp_copy', 0, 10, copy_target='allies_top_hp:1')
    e(2, 'cd', 'allies_top_atk:2', 'atk_pct', 0, 5)
    e(3, 'burst_cast', 'allies_top_atk:2', 'max_hp_pct', 0, 5)
    e(3, 'burst_cast', 'allies_top_atk:2', 'crit_dmg', 1, 10)
    kit('노이즈')
    e(1, 'received_hit:20', 'all_allies', 'received_dmg_pct', 0, 20, negative=True)
    e(2, 'full_charge_hit', 'target', 'taunt', duration=2)
    e(2, 'full_charge', 'self', 'max_hp_pct', 0, 1.8)
    heal(3, 'burst_cast', duration=10)
    e(3, 'burst_cast', 'all_allies', 'max_hp_pct', 1, 10)
    kit('아리아')
    e(1, 'full_burst_start', 'all_allies', 'crit_dmg', 0, 10)
    e(2, 'last_bullet', 'all_allies', 'crit_rate', 0, 5)
    shield(3, 'burst_cast', 'all_allies', duration=10)
    e(3, 'burst_cast', 'self', 'accuracy_pct', 1, 15)
    kit('아비스타')
    e(1, 'full_burst_end', 'allies_idol', 'atk_caster_based_pct', 0, -1, name='애프터 쇼')
    e(1, 'full_burst_start', 'allies_idol', 'remove_named_buff', target_effect='애프터 쇼')
    heal(1, 'full_burst_end', 'self', 1, 10)
    e(1, 'full_burst_end', 'self', 'remove_named_buff', target_effect='스타게이저')
    e(2, 'full_burst_start', 'self', 'hp_consume_pct', 20.0, condition='self_hp_above:25|self_state:스타게이저')
    pair(2, 'full_burst_start', 'allies_idol', [('projectile_explosion_dmg_pct', 0), ('atk_dmg_pct', 1)], -1, 'self_state:스타게이저')
    reenter(1); e(3, 'burst_cast', 'self', 'hp_caster_based_pct', 0, -1, name='스타게이저')
    kit('티아')
    e(1, 'event:cover_heal_received', 'self', 'burst_cooldown', 0, 12, stack=2)
    e(1, 'event:cover_heal_received', 'all_allies', 'atk_dmg_pct', 1, 10)
    e(2, 'hit_count:5', 'self', 'cover_max_hp_from_hp_pct', 0, 5)
    e(2, 'hit_count:5', 'self', 'taunt', duration=5, name='주목')
    e(2, 'burst_cast', 'self', 'cover_heal_hp_pct', 1)
    e(2, 'burst_cast', 'self', 'lifesteal_pct', 2, 10)
    shield(3, 'burst_cast', duration=10)
    shield(3, 'burst_cast', 'all_allies_excl_self', 1, 10); reenter(1)
    kit('일레그')
    e(1, 'battle_start', 'all_allies', 'projectile_dmg_pct', 0, -1)
    damage(1, 'hit_count:100', 'enemies_in_range', 1, 'target_state:붐 인스톨', stat='split_damage')
    e(2, 'hit_count:60', 'all_allies', 'atk_caster_based_pct', 0, 5, 'target_state:붐 인스톨')
    e(2, 'event:target_spawn', 'all_allies', 'burst_charge_pct', 100.0, max_trigger=1)
    e(3, 'burst_cast', 'all_allies', 'split_dmg_pct', 0, 10)
    damage(target='enemies_nearest:1', value=1)
    e(3, 'burst_cast', 'enemies_nearest:1', 'def_pct', 2, 10, name='붐 인스톨', negative=True)
    kit('트로니')
    e(1, 'full_charge_hit', 'enemies_nearest:1', 'damage_accumulate', 0, 5, 'not_target_state:T.Rony 봄버', name='T.Rony 봄버', accumulate_source='self', accumulate_ratio=50.0, detonate_at_cap=True)
    e(2, 'full_charge_fire_count:5', 'self', 'split_dmg_pct', 0, 10)
    e(2, 'full_charge_hit_count:5', 'target', 'def_pct', 1, 10, negative=True)
    pair(3, 'burst_cast', 'self', [('atk_pct', 0), ('accumulate_ratio_pct', 1)], 10)
    kit('크러스트')
    for state, idx in [('마이야르', 0), ('블렌칭', 1)]:
        e(1, 'full_charge', 'all_allies', 'buff_duration_extend', idx, condition=f'self_state:{state}', target_effect=state)
    for timing, idx, state, other in [('non_full_charge_fire_count:3', 2, '마이야르', '블렌칭'), ('charge_hold_count:1:3', 3, '블렌칭', '마이야르')]:
        e(1, timing, 'all_allies', 'atk_caster_based_pct', idx, 10, name=state)
        e(1, timing, 'all_allies', 'remove_named_buff', target_effect=other)
    for timing, idx in [('non_full_charge_fire_count:3', 0), ('charge_hold_count:1:3', 1)]:
        # Cleanse and defence share the same eligibility snapshot.
        e(2, timing, 'allies_without_buff:든든한 요리', 'debuff_cleanse', 1.0)
        e(2, timing, 'allies_without_buff:든든한 요리', 'def_caster_based_pct', idx, 10, name='든든한 요리')
    e(2, 'full_burst_start', 'allies_with_any_buff:마이야르,블렌칭', 'atk_caster_based_pct', 2, 10)
    e(3, 'burst_cast', 'all_allies', 'atk_dmg_pct', 0, 10)
    e(3, 'burst_cast', 'all_allies', 'split_dmg_pct', 1, 10, 'self_state:마이야르')
    e(3, 'burst_cast', 'all_allies', 'dot_dmg_pct', 2, 10, 'self_state:블렌칭')
    kit('소라')
    e(1, 'battle_start', 'self', 'heal_given_pct', 0, -1)
    e(2, 'event:part_destroy', 'all_allies', 'heal_overcharge_store', 0, 15, name='저장', stack=5)
    e(2, 'event:part_destroy', 'all_allies', 'atk_caster_based_pct', 1, 15)
    heal(3, 'burst_cast'); e(3, 'burst_cast', 'all_allies', 'debuff_cleanse', 1.0)
    for fav in range(4):
        kit('베이', fav)
        if fav in (0, 1):
            pair(1, 'burst_cast', 'all_allies', [('damage_share_weighted', None), ('def_caster_based_pct', 0)], -1, 'caster_alive')
            if fav: heal(1, 'full_charge', 'all_allies_excl_self', 1)
        if fav in (0, 2):
            e(2, 'burst_cast', 'self', 'cover_damage_share', duration=-1, condition='caster_alive')
            e(2, 'full_burst_end', 'self', 'cover_heal_hp_pct', 0, 5, tick_interval=1.0)
            if fav: heal(2, 'burst_enter:1', 'self', 1, condition='self_cover_broken')
        if fav in (0, 3):
            if fav: e(3, 'burst_cast', 'self', 'cover_revive_pct', 0, condition='self_cover_broken', max_trigger=1)
            e(3, 'burst_cast', 'self', 'cover_max_hp_from_hp_pct', 1 if fav else 0, 20)
            e(3, 'burst_cast', 'all_allies', 'received_dmg_pct', 2 if fav else 1, 10, negative=True)
    kit('클레이')
    e(1, 'on_attack_count:60', 'all_allies', 'armor_break_dmg_pct', 0, 6, 'during_full_burst', name='승리의 외침', stack=3)
    e(1, 'on_attack_count:60', 'all_allies', 'projectile_dmg_pct', 1, 6, 'during_full_burst')
    e(2, 'burst_enter:1', 'all_allies', 'debuff_block_charge', 1.0, 10)
    e(2, 'passive', 'all_allies', 'atk_caster_based_pct', 0, -1, 'self_state:승리의 외침')
    e(3, 'burst_cast', 'all_allies', 'armor_break_dmg_pct', 0, 10)
    e(3, 'burst_cast', 'self', 'armor_break_enabled', duration=10)
    kit('레이블')
    shield(1, 'battle_start', name='망상')
    e(1, 'event:state_end:망상', 'self', 'gauge_charge', 1.0, gauge_id='망상 파괴', gauge_max=2)
    pair(1, 'event:state_end:망상', 'self', [('stealth', None), ('stun', None)], -1, duration_scaling_ref='망상 파괴')
    shield(1, 'on_attack', value=1, condition='not_self_state:망상', name='망상')
    shield(1, 'burst_cast', value=2, condition='not_self_state:망상', name='망상')
    e(2, 'battle_start', 'all_allies_excl_self', 'received_dmg_from_code:전격', 0, 5, negative=True, max_trigger=1)
    pair(2, 'passive', 'self', [('burst_charge_speed_pct', 1), ('atk_pct', 2)], -1, 'self_state:망상')
    e(2, 'passive', 'self', 'received_dmg_from_code:전격', 3, -1, 'self_state:망상', negative=True)
    e(2, 'passive', 'all_allies_excl_self', 'atk_caster_based_pct', 4, -1, 'self_state:망상 공유')
    e(3, 'burst_cast', 'self', 'max_hp_pct', 0, 10)
    e(3, 'burst_cast', 'self', 'shield_invincible', duration=10, name='망상 공유')
    kit('모리')
    shield(1, 'battle_start', name='발버둥')
    shield(1, 'burst_cast', value=1, condition='not_self_state:발버둥', name='발버둥')
    e(1, 'event:state_end:발버둥', 'self', 'max_hp_pct', 2, -1, stack=5)
    e(2, 'hit_count:60', 'target', 'taunt', duration=4, condition='self_state:발버둥')
    e(2, 'event:part_destroy', 'all_allies', 'dot_dmg_pct', 0, 15, stack=5)
    damage(2, 'event:part_destroy', 'enemies_top_atk:1', 1, stat='dot_damage', duration=15, tick_interval=1.0)
    e(3, 'burst_cast', 'self', 'shield_restore_pct', 0, condition='self_state:발버둥')
    e(3, 'burst_cast', 'self', 'max_hp_pct', 1, 10, 'not_self_state:발버둥')
    e(3, 'burst_cast', 'all_allies', 'dot_dmg_pct', 2, 10)
    kit('백학')
    e(1, 'passive', 'all_allies', 'hp_caster_based_pct', 0, -1, 'not_self_state:서약 해지', name='회복 독점 서약')
    e(1, 'event:heal_received', 'self', 'heal_given_pct', 1, -1, 'healed_by_other|not_self_state:서약 해지', name='서약 위반 증거', stack=3, negative=True)
    heal(2, 'full_charge_fire_count:3', 'allies_with_buff:회복 독점 서약')
    shield(2, 'full_burst_start', 'all_allies', 1, 10)
    e(2, 'event:서약 위반 증거', 'self', None, duration=-1, condition='self_stack_above:서약 위반 증거:3', name='서약 해지')
    heal(2, 'event:서약 해지', 'self', 2, -1)
    heal(3, 'burst_cast'); e(3, 'burst_cast', 'self', 'pierce_enabled', duration=10)
    kit('마키마')
    pair(1, 'received_hit:20', 'all_allies', [('reload_speed_pct', 0), ('def_pct', 1)], 10)
    e(2, 'on_attack_count:120', 'self', 'taunt', duration=3, name='주목')
    e(2, 'event:lethal_hit', 'self', 'undying', duration=7, name='불굴', max_trigger=1)
    e(2, 'event:lethal_hit', 'self', 'burst_cooldown_reduce', 0, max_trigger=1)
    pair(3, 'burst_cast', 'self', [('pierce_enabled', None), ('lifesteal_pct', 0)], 10)
    e(3, 'burst_cast', 'self', 'heal_received_pct', 1, 10, 'self_state:불굴')
    kit('파워')
    e(1, 'full_charge', 'self', 'atk_pct', 0, 3, name='피의 마인', stack=5)
    e(2, 'on_attack_count:18', 'self', 'explosion_range', 0, 10, 'self_stack_above:피의 마인:5')
    e(2, 'on_attack_count:18', 'self', 'ammo_charge_pct', 100.0, condition='self_stack_above:피의 마인:5', max_trigger=1)
    damage(target='enemies_top_atk:1'); damage(target='enemies_top_atk:1', value=1, condition='self_stack_above:피의 마인:5', stat='bonus_damage')
    kit('히메노')
    e(1, 'full_charge_hit', 'target', 'def_pct', 0, 3, negative=True)
    pair(2, 'cd', 'allies_weapon:SR', [('atk_pct', 0), ('max_ammo_flat', 2.0)], 10)
    pair(3, 'burst_cast', 'allies_top_atk_excl:1', [('charge_dmg_pct', 0), ('crit_rate', 1)], 10)
    kit('2B')
    for i in range(3): e(1, f'burst_cast_count:{i+1}', 'self', 'max_hp_pct', i, -1)
    damage(2, 'on_attack_count:300', 'all_enemies', stat='damage')
    e(2, 'battle_start', 'self', 'atk_from_hp_pct', 1, -1)
    damage(stat='split_damage'); damage(target='enemies_top_hp:1', value=1, stat='bonus_damage')
    kit('A2')
    pair(1, 'burst_cast', 'self', [('charge_dmg_pct', 0), ('explosion_range', 1)], 15)
    damage(2, 'full_charge_hit', 'target', stat='bonus_damage')
    e(2, 'full_charge_hit', 'self', 'part_dmg_pct', 1, 3)
    e(3, 'burst_cast', 'self', None, duration=-1, name='B 모드')
    e(3, 'hp_below:40', 'self', 'remove_named_buff', target_effect='B 모드')
    e(3, 'burst_cast', 'self', 'hp_consume_pct', 0, -1, 'self_state:B 모드', tick_interval=1.0)
    pair(3, 'passive', 'self', [('atk_pct', 1), ('charge_speed_pct', 2)], -1, 'self_state:B 모드')
    kit('파스칼')
    heal(1, 'on_attack_count:10', 'allies_top_def:1')
    e(2, 'burst_enter:1', 'allies_lowest_hp:3', 'heal_received_pct', 0, 10)
    heal(3, 'burst_cast', 'allies_lowest_hp:3')
    kit('렘')
    e(1, 'hit_count:15', 'self', 'atk_pct', 0, 10, 'self_state:도깨비 기운', stack=30)
    e(1, 'burst_cast', 'all_allies', 'heal_split', duration=10)
    e(2, 'battle_start', 'self', 'lifesteal_pct', 0, -1)
    e(2, 'battle_start', 'self_and_weapon_top_atk:RL:2', 'heal_split', duration=-1)
    e(3, 'burst_cast', 'self', 'crit_rate', 0, 10, name='도깨비 기운')
    pair(3, 'burst_cast', 'allies_weapon:RL', [('atk_caster_based_pct', 1), ('max_ammo_flat', 2)], 10)
    kit('에밀리아')
    e(1, 'full_charge', 'self', 'charge_speed_pct', 0, bullets=1)
    e(1, 'full_charge', 'self', 'charge_dmg_pct', 1, bullets=1, scaling='max_ammo')
    damage(2, 'full_charge_hit', 'target_body', stat='copy_hit_damage')
    e(2, 'full_burst_start', 'self', 'max_ammo_flat', 1, 10)
    e(3, 'burst_cast', 'self', 'explosion_range', 0, 10)
    pair(3, 'burst_cast', 'self', [('charge_speed_pct', -300.0), ('charge_dmg_pct', 1)], -1, bullets=1)
    kit('람')
    e(1, 'hit_count:5', 'target', 'atk_pct', 0, 5, negative=True)
    e(1, 'full_burst_end', 'self', 'burst_cooldown_reduce', 20.16, condition='squad_ally_exists')
    e(2, 'cd', 'self', 'max_hp_only_pct', 0, 10)
    e(2, 'cd', 'allies_lowest_hp:2', 'def_caster_based_pct', 1, 5)
    shield(3, 'burst_cast', 'all_allies', duration=10)
    kit('마리')
    e(1, 'full_charge', 'all_allies', 'shield_dmg_pct', 0, 3)
    e(1, 'core_hit_count:1', 'all_allies', 'pierce_dmg_pct', 1, 10)
    pair(2, 'cd', 'self', [('pierce_enabled', None), ('atk_pct', 0)], 5)
    e(2, 'cd', 'all_allies', 'atk_caster_based_pct', 1, 5)
    damage(); e(3, 'burst_cast', 'all_allies', 'atk_dmg_pct', 1, 10)
    kit('미사토')
    e(1, 'on_attack_count:60', 'self', 'accuracy_pct', 0, 5, name='사격 매뉴얼', stack=3)
    heal(1, 'on_attack_count:120', 'allies_lowest_hp_ratio:1', 1)
    e(2, 'passive', 'all_allies', 'shield_dmg_pct', 0, -1, 'self_state:사격 매뉴얼')
    e(2, 'passive', 'self', 'heal_given_pct', 1, -1, 'self_stack_above:사격 매뉴얼:3')
    heal(3, 'burst_cast', duration=5)
    kit('사쿠라 (SR)')
    e(1, 'hit_count:120', 'target', 'received_dmg_pct', 0, 5)
    e(2, 'on_attack_count:60', 'allies_lowest_hp_ratio:2', 'heal_received_pct', 0, 10)
    e(2, 'on_attack_count:120', 'allies_lowest_hp_ratio:2', 'received_dmg_pct', 1, 10, negative=True)
    heal(3, 'burst_cast', 'allies_lowest_hp_ratio:2', duration=10)
    kit('클레어')
    heal(1, 'full_charge_hit_count:3', 'allies_top_atk:2')
    shield(2, 'burst_cast', 'all_allies', duration=10)
    heal(3, 'burst_cast'); e(3, 'burst_cast', 'all_allies', 'debuff_cleanse', 1.0)
    kit('릴리')
    e(1, 'cd', 'allies_random:1', 'atk_caster_based_pct', 0, 5)
    e(2, 'cd', 'all_allies', 'cover_heal_pct', 0)
    e(3, 'burst_cast', 'allies_random:1', 'atk_caster_based_pct', 2, 10, 'no_broken_ally_cover')
    e(3, 'burst_cast', 'allies_broken_cover_random:1', 'atk_caster_based_pct', 1, 10, name='엄폐물 부활 대상')
    e(3, 'burst_cast', 'allies_with_buff:엄폐물 부활 대상', 'cover_revive_pct', 0)
    kit('쿠루미')
    damage(1, ['hit_count:36', 'burst_cast'], 'all_enemies', stat='dot_damage', duration=5, tick_interval=1.0, name='해킹')
    # Both source clauses use exactly the same coefficient at every skill level.
    assert values(1, 0) == values(1, 1)
    damage(2, 'hit_count:36', 'target', condition='during_full_burst|target_state:해킹', stat='bonus_damage')
    e(3, 'burst_cast', 'all_enemies', 'received_dmg_pct', 0, 10)
    kit('아이기스')
    e(1, 'battle_start', 'self', 'persona_state', duration=-1, name='페르소나 - 팔라디온', undispellable=True)
    pair(1, 'battle_start', 'self', [('atk_pct', 0), ('def_pct', 1)], -1, undispellable=True)
    e(2, 'burst_cast', 'self', None, duration=-1, name='파피용 하트', undispellable=True)
    e(2, 'full_burst_end', 'self', 'remove_named_buff', target_effect='파피용 하트')
    pair(2, 'passive', 'all_allies', [('atk_caster_based_pct', 0), ('def_caster_based_pct', 1)], -1, 'caster_alive|self_state:파피용 하트', undispellable=True)
    damage(stat='split_damage')
    kit('K')
    e(1, 'last_bullet_fire', 'self', 'crit_rate', 0, -1, name='기울어지는 천칭', stack=100)
    e(1, 'last_bullet_fire', 'self', 'buff_stack_add', 1, target_effect='기울어지는 천칭')
    damage(1, 'crit_pellet_hit_count:4', 'target', 2, stat='bonus_damage')
    e(1, 'full_burst_end', 'self', 'remove_named_buff', target_effect='기울어지는 천칭')
    e(2, 'event:기울어지는 천칭', 'all_allies', 'max_ammo_pct', 0, 10, name='정의 실현', negative=True, nonstacking_group='magazine_reduction')
    e(2, 'event:기울어지는 천칭', 'all_allies', 'atk_dmg_pct', 1, 10, name='정의 실현 공격')
    for state in ['정의 실현', '정의 실현 공격']:
        e(2, 'full_burst_end', 'all_allies', 'remove_named_buff', target_effect=state)
    # Native shot 1004102: 144 rounds/minute; two muzzles, five pellets each.
    weapon(3, 0, 'SG', 10, pellets=5, muzzles=2, fire_rate=2.4, max_ammo=999,
           burst_energy=0.2)
    pair(3, 'burst_cast', 'self', [('atk_caster_based_pct', 1), ('atk_dmg_pct', 2)], 10)


def main():
    build()
    path = ROOT / 'data/parsed_skills.json'
    parsed = json.loads(path.read_text(encoding='utf-8'))
    parsed.update(KITS)
    for name in ('엠마 : 택티컬 업', '은화 : 택티컬 업', '베스티 : 택티컬 업'):
        for effect in parsed[name]:
            if 'passive' in effect['trigger']['timing']:
                conditions = effect['trigger'].setdefault('condition', [])
                if 'caster_alive' not in conditions:
                    conditions.append('caster_alive')
    path.write_text(json.dumps(parsed, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'Compiled {len(KITS)} kits, {sum(map(len, KITS.values()))} effects from canonical level tables.')


if __name__ == '__main__':
    main()
